// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"context"
	"red-bean-anime-server/internal/app/gateway"
	"red-bean-anime-server/pkg/config"
	"red-bean-anime-server/pkg/db/etcd"
	"red-bean-anime-server/pkg/log"
)

// Injectors from wire.go:

func New(ctx context.Context, filepath string) (*gateway.Gateway, error) {
	viper, err := config.NewConfig(filepath)
	if err != nil {
		return nil, err
	}
	client, err := etcd.NewEtcd(viper)
	if err != nil {
		return nil, err
	}
	logger, err := log.NewLog(viper)
	if err != nil {
		return nil, err
	}
	gatewayGateway := gateway.NewGateway(ctx, client, viper, logger)
	return gatewayGateway, nil
}
