// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/user/user.proto

package userpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LoginInfo struct {
	Phone                string   `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginInfo) Reset()         { *m = LoginInfo{} }
func (m *LoginInfo) String() string { return proto.CompactTextString(m) }
func (*LoginInfo) ProtoMessage()    {}
func (*LoginInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_3bc452c1a8bd0aa8, []int{0}
}

func (m *LoginInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginInfo.Unmarshal(m, b)
}
func (m *LoginInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginInfo.Marshal(b, m, deterministic)
}
func (m *LoginInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginInfo.Merge(m, src)
}
func (m *LoginInfo) XXX_Size() int {
	return xxx_messageInfo_LoginInfo.Size(m)
}
func (m *LoginInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginInfo.DiscardUnknown(m)
}

var xxx_messageInfo_LoginInfo proto.InternalMessageInfo

func (m *LoginInfo) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *LoginInfo) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type RegisterReq struct {
	Phone                string   `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterReq) Reset()         { *m = RegisterReq{} }
func (m *RegisterReq) String() string { return proto.CompactTextString(m) }
func (*RegisterReq) ProtoMessage()    {}
func (*RegisterReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_3bc452c1a8bd0aa8, []int{1}
}

func (m *RegisterReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterReq.Unmarshal(m, b)
}
func (m *RegisterReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterReq.Marshal(b, m, deterministic)
}
func (m *RegisterReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterReq.Merge(m, src)
}
func (m *RegisterReq) XXX_Size() int {
	return xxx_messageInfo_RegisterReq.Size(m)
}
func (m *RegisterReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterReq.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterReq proto.InternalMessageInfo

func (m *RegisterReq) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *RegisterReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *RegisterReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type LoginRes struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRes) Reset()         { *m = LoginRes{} }
func (m *LoginRes) String() string { return proto.CompactTextString(m) }
func (*LoginRes) ProtoMessage()    {}
func (*LoginRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_3bc452c1a8bd0aa8, []int{2}
}

func (m *LoginRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRes.Unmarshal(m, b)
}
func (m *LoginRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRes.Marshal(b, m, deterministic)
}
func (m *LoginRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRes.Merge(m, src)
}
func (m *LoginRes) XXX_Size() int {
	return xxx_messageInfo_LoginRes.Size(m)
}
func (m *LoginRes) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRes.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRes proto.InternalMessageInfo

func (m *LoginRes) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type UserInfoRes struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Phone                string   `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfoRes) Reset()         { *m = UserInfoRes{} }
func (m *UserInfoRes) String() string { return proto.CompactTextString(m) }
func (*UserInfoRes) ProtoMessage()    {}
func (*UserInfoRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_3bc452c1a8bd0aa8, []int{3}
}

func (m *UserInfoRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfoRes.Unmarshal(m, b)
}
func (m *UserInfoRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfoRes.Marshal(b, m, deterministic)
}
func (m *UserInfoRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfoRes.Merge(m, src)
}
func (m *UserInfoRes) XXX_Size() int {
	return xxx_messageInfo_UserInfoRes.Size(m)
}
func (m *UserInfoRes) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfoRes.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfoRes proto.InternalMessageInfo

func (m *UserInfoRes) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UserInfoRes) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserInfoRes) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

type UserInfoList struct {
	UserinfoList         []*UserInfoRes `protobuf:"bytes,1,rep,name=userinfoList,proto3" json:"userinfoList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *UserInfoList) Reset()         { *m = UserInfoList{} }
func (m *UserInfoList) String() string { return proto.CompactTextString(m) }
func (*UserInfoList) ProtoMessage()    {}
func (*UserInfoList) Descriptor() ([]byte, []int) {
	return fileDescriptor_3bc452c1a8bd0aa8, []int{4}
}

func (m *UserInfoList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfoList.Unmarshal(m, b)
}
func (m *UserInfoList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfoList.Marshal(b, m, deterministic)
}
func (m *UserInfoList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfoList.Merge(m, src)
}
func (m *UserInfoList) XXX_Size() int {
	return xxx_messageInfo_UserInfoList.Size(m)
}
func (m *UserInfoList) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfoList.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfoList proto.InternalMessageInfo

func (m *UserInfoList) GetUserinfoList() []*UserInfoRes {
	if m != nil {
		return m.UserinfoList
	}
	return nil
}

type Id struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Id) Reset()         { *m = Id{} }
func (m *Id) String() string { return proto.CompactTextString(m) }
func (*Id) ProtoMessage()    {}
func (*Id) Descriptor() ([]byte, []int) {
	return fileDescriptor_3bc452c1a8bd0aa8, []int{5}
}

func (m *Id) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Id.Unmarshal(m, b)
}
func (m *Id) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Id.Marshal(b, m, deterministic)
}
func (m *Id) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Id.Merge(m, src)
}
func (m *Id) XXX_Size() int {
	return xxx_messageInfo_Id.Size(m)
}
func (m *Id) XXX_DiscardUnknown() {
	xxx_messageInfo_Id.DiscardUnknown(m)
}

var xxx_messageInfo_Id proto.InternalMessageInfo

func (m *Id) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func init() {
	proto.RegisterType((*LoginInfo)(nil), "LoginInfo")
	proto.RegisterType((*RegisterReq)(nil), "RegisterReq")
	proto.RegisterType((*LoginRes)(nil), "LoginRes")
	proto.RegisterType((*UserInfoRes)(nil), "UserInfoRes")
	proto.RegisterType((*UserInfoList)(nil), "UserInfoList")
	proto.RegisterType((*Id)(nil), "Id")
}

func init() { proto.RegisterFile("api/user/user.proto", fileDescriptor_3bc452c1a8bd0aa8) }

var fileDescriptor_3bc452c1a8bd0aa8 = []byte{
	// 369 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x91, 0x4f, 0x4a, 0xc3, 0x40,
	0x14, 0xc6, 0x49, 0x62, 0x25, 0x79, 0x09, 0x45, 0xa6, 0xa5, 0xc4, 0xe8, 0xa2, 0xcc, 0xaa, 0xb8,
	0x98, 0x68, 0x05, 0x17, 0x8a, 0x20, 0x82, 0x48, 0xb1, 0xab, 0x14, 0x37, 0xee, 0x52, 0x33, 0x8d,
	0x83, 0xed, 0x4c, 0xcc, 0xa4, 0x8a, 0x5b, 0xaf, 0xe0, 0x99, 0x3c, 0x81, 0x57, 0xf0, 0x20, 0x32,
	0x33, 0x49, 0xff, 0xb8, 0x73, 0x13, 0xf2, 0xcd, 0x9b, 0xf7, 0x9b, 0xef, 0x7b, 0x0f, 0x3a, 0x69,
	0xc1, 0xe2, 0xa5, 0xa4, 0xa5, 0xfe, 0x90, 0xa2, 0x14, 0x95, 0x88, 0x0e, 0x72, 0x21, 0xf2, 0x39,
	0x8d, 0xb5, 0x9a, 0x2e, 0x67, 0x31, 0x5d, 0x14, 0xd5, 0x7b, 0x5d, 0x3c, 0xac, 0x8b, 0xaa, 0x31,
	0xe5, 0x5c, 0x54, 0x69, 0xc5, 0x04, 0x97, 0xa6, 0x8a, 0x2f, 0xc1, 0x1b, 0x8b, 0x9c, 0xf1, 0x11,
	0x9f, 0x09, 0xd4, 0x85, 0x56, 0xf1, 0x24, 0x38, 0x0d, 0xad, 0xbe, 0x35, 0xf0, 0x12, 0x23, 0x50,
	0x04, 0x6e, 0x91, 0x4a, 0xf9, 0x26, 0xca, 0x2c, 0xb4, 0x75, 0x61, 0xa5, 0xf1, 0x04, 0xfc, 0x84,
	0xe6, 0x4c, 0x56, 0xb4, 0x4c, 0xe8, 0xcb, 0xff, 0x01, 0x08, 0xc1, 0x0e, 0x4f, 0x17, 0x34, 0x74,
	0xf4, 0xb9, 0xfe, 0xc7, 0x7d, 0x70, 0xb5, 0xa7, 0x84, 0x4a, 0x45, 0xac, 0xc4, 0x33, 0xe5, 0x0d,
	0x51, 0x0b, 0x7c, 0x0b, 0xfe, 0xbd, 0xa4, 0xa5, 0x32, 0xad, 0x2e, 0xb5, 0xc1, 0x66, 0x99, 0xbe,
	0xe1, 0x24, 0x36, 0x5b, 0x43, 0xed, 0x35, 0x74, 0x6d, 0xcd, 0xd9, 0xb0, 0x86, 0xaf, 0x20, 0x68,
	0x40, 0x63, 0x26, 0x2b, 0x74, 0x0c, 0x81, 0x9a, 0x2b, 0xab, 0x75, 0x68, 0xf5, 0x9d, 0x81, 0x3f,
	0x0c, 0xc8, 0xc6, 0x6b, 0xc9, 0xd6, 0x0d, 0xdc, 0x05, 0x7b, 0x94, 0xfd, 0x75, 0x30, 0xfc, 0xb2,
	0x8c, 0xc3, 0x09, 0x2d, 0x5f, 0xd9, 0x23, 0x45, 0x67, 0xd0, 0xd2, 0x91, 0x10, 0x90, 0xd5, 0xb8,
	0x23, 0x8f, 0x34, 0x31, 0x71, 0xef, 0xe3, 0xfb, 0xe7, 0xd3, 0xde, 0xc3, 0xbe, 0xd9, 0xed, 0x5c,
	0x9d, 0x9f, 0x5b, 0x47, 0xe8, 0x0e, 0xdc, 0x66, 0xbe, 0x28, 0x20, 0x1b, 0xa3, 0x8e, 0x7a, 0xc4,
	0xec, 0x95, 0x34, 0x4b, 0x27, 0x37, 0x6a, 0xe9, 0x78, 0x5f, 0x93, 0x3a, 0xb8, 0x6d, 0x48, 0x65,
	0xdd, 0xa2, 0x60, 0x27, 0xe0, 0x36, 0x39, 0x90, 0x43, 0x46, 0x59, 0xb4, 0x95, 0x0b, 0x23, 0xdd,
	0x19, 0x20, 0x30, 0x9d, 0x2a, 0xe1, 0xb5, 0xff, 0xe0, 0x91, 0xf8, 0x42, 0xe9, 0x62, 0x3a, 0xdd,
	0xd5, 0x4f, 0x9d, 0xfe, 0x06, 0x00, 0x00, 0xff, 0xff, 0x15, 0x72, 0xb2, 0xe1, 0x84, 0x02, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	Login(ctx context.Context, in *LoginInfo, opts ...grpc.CallOption) (*LoginRes, error)
	Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	UserInfo(ctx context.Context, in *Id, opts ...grpc.CallOption) (*UserInfoRes, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) Login(ctx context.Context, in *LoginInfo, opts ...grpc.CallOption) (*LoginRes, error) {
	out := new(LoginRes)
	err := c.cc.Invoke(ctx, "/UserService/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/UserService/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UserInfo(ctx context.Context, in *Id, opts ...grpc.CallOption) (*UserInfoRes, error) {
	out := new(UserInfoRes)
	err := c.cc.Invoke(ctx, "/UserService/UserInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	Login(context.Context, *LoginInfo) (*LoginRes, error)
	Register(context.Context, *RegisterReq) (*emptypb.Empty, error)
	UserInfo(context.Context, *Id) (*UserInfoRes, error)
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/UserService/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Login(ctx, req.(*LoginInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/UserService/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Register(ctx, req.(*RegisterReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/UserService/UserInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UserInfo(ctx, req.(*Id))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _UserService_Login_Handler,
		},
		{
			MethodName: "Register",
			Handler:    _UserService_Register_Handler,
		},
		{
			MethodName: "UserInfo",
			Handler:    _UserService_UserInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/user/user.proto",
}
