// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"red-bean-anime-server/internal/app/file/service"
	"red-bean-anime-server/internal/app/file/usecase"
)

// Injectors from wire.go:

func NewService() *service.FileService {
	iFileUsecase := usecase.NewFileUsecase()
	fileService := service.NewFileService(iFileUsecase)
	return fileService
}
