// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"context"
	"red-bean-anime-server/internal/app/gateway"
	"red-bean-anime-server/internal/pkg/cache"
	"red-bean-anime-server/internal/pkg/config"
)

// Injectors from wire.go:

func New(ctx context.Context, filepath string) (*gateway.Gateway, error) {
	viper, err := config.NewConfig(filepath)
	if err != nil {
		return nil, err
	}
	client, err := cache.NewEtcd(viper)
	if err != nil {
		return nil, err
	}
	gatewayGateway := gateway.NewGateway(ctx, client, viper)
	return gatewayGateway, nil
}
